#
# Makefile for the Goodix touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_NUBIA_GT1X_TOUCHSCREEN_DRIVER)	+=  gt1x.o \
												gt1x_update.o \
												gt1x_tools.o \
												gt1x_extents.o \
												gt1x_generic.o \
												gt1x_test.o \
												test_function.o
